(function(g){var window=this;'use strict';var r$a=function(a,b){if(!Number.isFinite(a))return String(a);a=String(a);var c=a.indexOf(".");-1===c&&(c=a.length);var d="-"===a[0]?"-":"";d&&(a=a.substring(1));return d+(0,g.n2a)("0",Math.max(0,b-c))+a},s$a=function(){return{F:"svg",
X:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},W:[{F:"path",X:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},t$a=function(){return{F:"svg",
X:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},W:[{F:"path",X:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},v$a=function(a){"number"===typeof a?(this.date=u$a(a,0,1),y6(this,1)):g.Ma(a)?(this.date=u$a(a.getFullYear(),a.getMonth(),a.getDate()),y6(this,a.getDate())):(this.date=new Date(g.Sa()),a=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),y6(this,a))},u$a=function(a,b,c){b=new Date(a,b,c);
0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b},y6=function(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))},z6=function(a,b){g.QO.call(this,a,{F:"div",
K:"ytp-reminder-menu",X:{role:"menu",tabindex:"-1"},W:[{F:"div",K:"ytp-reminder-menu-contents",W:[{F:"div",K:"ytp-reminder-menu-items"}]}]},100,!0);this.buttonElement=b;this.j=[];this.menuPopupRenderer=void 0;this.items=this.Da("ytp-reminder-menu-items");this.hide()},x$a=function(a){var b=w$a(a),c=0,d={};
for(c=0;c<b.length;d={BF:d.BF},c++){var e=a.j[c];e||(e=new g.V({F:"div",K:"ytp-reminder-menu-item",X:{role:"menuitem",tabindex:"0"},W:[{F:"div",K:"ytp-reminder-menu-item-icon",qa:"{{icon}}"},{F:"div",K:"ytp-reminder-menu-item-label",qa:"{{text}}"}]}),d.BF=c,e.Pa("click",function(l){return function(){var m=l.BF;a.wb();m=w$a(a)[m];a.ma("reminderMenuItemClicked",m.serviceEndpoint||m.command)}}(d)),e.Ca(a.items),a.j[c]=e);
var f=b[c],h=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":h=s$a();break;case "NOTIFICATIONS_NONE":h=t$a();break;case "NOTIFICATIONS_ACTIVE":h=g.oM()}f=f.text?g.dB(f.text):"";e.update({icon:h,text:f})}for(;c<a.j.length;)a.j.pop().dispose();0===c?a.wb():a.Kc(a.buttonElement)},w$a=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},A6=function(a){g.V.call(this,{F:"div",
W:[{F:"button",Ga:["ytp-offline-slate-button","ytp-button"],W:[{F:"div",K:"ytp-offline-slate-button-icon",qa:"{{icon}}"},{F:"div",K:"ytp-offline-slate-button-text",qa:"{{text}}"}]}]});this.G=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.u=void 0;this.C=this.j=null;(this.buttonElement=this.Da("ytp-offline-slate-button"))&&this.S(this.buttonElement,"click",this.D);this.hide()},z$a=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=
b.toggleButtonRenderer:b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&g.O(c,y$a)?a.upcomingEventReminderButtonRenderer=g.O(c,y$a):c&&g.O(c,y$a)||(a.upcomingEventReminderButtonRenderer=null);B6(a)},B6=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.dB(b.toggledText):"";a.update({text:c,icon:A$a(b.toggledIcon)})}else c=b.defaultText?g.dB(b.defaultText):"",a.update({text:c,icon:A$a(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=B$a(a))?(c=b.text?g.dB(b.text):"",a.update({text:c,icon:A$a(b.icon)}),a.show()):a.hide():a.hide()},D$a=function(a,b,c){a.C||(a.C=new g.ux(a.G.V().Pi));
var d={context:g.Vw(a.C.config_||g.Uw())};g.gA()&&(d.context.clientScreenNonce=g.gA());d.params=c;g.vx(a.C,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.u&&(a.upcomingEventReminderButtonRenderer.currentState=a.u,a.u=void 0)},
onError:function(){C$a(a)},
onTimeout:function(){C$a(a)}})},C$a=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,B6(a)):a.upcomingEventReminderButtonRenderer&&(a.u=void 0,B6(a))},A$a=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return s$a();case "NOTIFICATIONS_NONE":return t$a();case "NOTIFICATIONS_ACTIVE":return g.oM();default:return null}},B$a=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.u||a.upcomingEventReminderButtonRenderer.currentState;a=g.t(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=g.O(c.value,E$a))&&c.state===b&&c.button&&g.O(c.button,g.LI))return g.O(c.button,g.LI);return null},F$a=function(a){g.V.call(this,{F:"div",
K:"ytp-offline-slate",W:[{F:"div",K:"ytp-offline-slate-background"},{F:"div",K:"ytp-offline-slate-bar",W:[{F:"span",K:"ytp-offline-slate-icon",W:[{F:"svg",X:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},W:[{F:"path",X:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{F:"circle",X:{cx:"12",cy:"12",r:"3"}}]}]},{F:"span",K:"ytp-offline-slate-messages",W:[{F:"div",K:"ytp-offline-slate-main-text",X:{"aria-label":"{{label}}"},qa:"{{mainText}}"},{F:"div",K:"ytp-offline-slate-subtitle-text",qa:"{{subtitleText}}"}]},{F:"span",K:"ytp-offline-slate-buttons"}]},{F:"button",Ga:["ytp-offline-slate-close-button","ytp-button"],W:[g.jM()]},{F:"button",Ga:["ytp-offline-slate-open-button","ytp-button"],W:[g.iM()]}]});var b=this;this.api=a;this.j=this.u=null;this.background=this.Da("ytp-offline-slate-background");
this.B=this.Da("ytp-offline-slate-bar");this.D=new g.co(function(){g.lo(b.B,"ytp-offline-slate-bar-fade")},15E3);
this.I=!1;this.C=new g.co(function(){g.lo(b.element,"ytp-offline-slate-collapsed")},15E3);
g.M(this,this.C);g.M(this,this.D);this.countdownTimer=new g.co(this.pU,1E3,this);this.S(a,"presentingplayerstatechange",this.tU);this.S(a,"livestatedata",this.La);var c=this.Da("ytp-offline-slate-close-button");this.S(c,"click",function(){g.lo(b.element,"ytp-offline-slate-collapsed")});
c=this.Da("ytp-offline-slate-open-button");this.S(c,"click",function(){g.no(b.element,"ytp-offline-slate-collapsed")});
this.hide();c=this.getVideoData();c.getPlayerResponse()&&(c=c.getPlayerResponse().playabilityStatus)&&this.La(c);c=8===this.api.getPresentingPlayerType()&&!this.getVideoData().hk;var d=8===this.api.getPresentingPlayerType();g.po(this.element,"ytp-offline-slate-premiere-trailer",c);g.po(this.element,"ytp-offline-slate-hide-background",d);a.N("web_rounded_containers")&&g.lo(this.B,"ytp-rounded-offline-slate")},G$a=function(a,b,c){if(b){var d=null!=b.subtitleText?g.dB(b.subtitleText):"";
c=c?c:null!=b.mainText?g.dB(b.mainText):"";var e,f,h,l;b=null!=(l=null==(e=b.mainText)?void 0:null==(f=e.accessibility)?void 0:null==(h=f.accessibilityData)?void 0:h.label)?l:c;a.update({mainText:c,subtitleText:d,label:b});g.po(a.element,"ytp-offline-slate-single-text-line",!d);g.po(a.B,"ytp-offline-slate-bar-hidden",!c&&!d)}},C6=function(a,b){var c=(0,g.Q)();
this.module="heartbeat";this.trigger=a;this.j=b;this.B=c},O$a=function(a){g.vP.call(this,a);
var b=this;this.J=!1;this.T=0;this.D=!1;this.u=new g.co(function(){var e=b.player.V(),f=b.getVideoData();D6(b)&&(H$a(b)?I$a(b,e,f):(J$a(b),K$a(b,e,f)))},0);
this.j=this.heartbeatParams=null;this.C=!1;this.I=new g.Th(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.ea=new g.ux(void 0);this.Y=this.attestationResponse=void 0;this.utcOffsetMinutes=-(new v$a).getTimezoneOffset();this.B=new g.QE(this);g.M(this,this.u);g.M(this,this.B);J$a(this);L$a(this);this.B.S(a,"heartbeatparams",this.zA);this.B.S(a,"presentingplayerstatechange",this.IV);this.B.S(a,"videoplayerreset",this.JV);this.B.S(a,g.ZA("heartbeat"),this.onCueRangeEnter);this.C&&this.j&&
M$a(this,this.j);var c=new g.XA(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),d=new g.XA(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});a.xe([c,d]);N$a(this)},N$a=function(a){var b=a.getVideoData();
b.il&&(b=b.botguardData)&&g.YN(b,a.player.V())},J$a=function(a){var b=a.getVideoData();
if(b.il&&(b=new g.jIa(b),g.PN.isInitialized()||3<=a.sequenceNumber)){var c=null;if(b.videoData.tj){var d=g.kIa(b);if(d){c={};var e={};d=d.split("&");d=g.t(d);for(var f=d.next();!f.done;f=d.next())f=f.value.split("="),2===f.length&&(e[f[0]]=f[1]);e.r1a&&(c.webResponse=e.r1a);e.r1c&&(c.error=P$a[Number(e.r1c)]);c.challenge=b.videoData.tj}}a.attestationResponse=c||void 0}},H$a=function(a){var b=a.getVideoData();
if(!g.XI(a.getVideoData())||b.wO)return!1;if(b.useInnertubeDrmService()&&b.Y){a="playready"===b.Y.flavor&&b.N("html5_innertube_heartbeats_for_playready");var c="widevine"===b.Y.flavor&&b.N("html5_innertube_heartbeats_for_widevine");b=g.PF(b.Y)&&b.N("html5_innertube_heartbeats_for_fairplay");return!(a||c||b)}return!0},Q$a=function(a){if(H$a(a))return!!a.heartbeatParams;
var b=a.getVideoData();return g.XI(a.getVideoData())&&b.useInnertubeDrmService()&&!b.Wk&&!b.VF?!1:!!b.heartbeatToken},E6=function(a,b){if(!a.u.isActive()&&a.J){var c=a.getVideoData();
if(Q$a(a)||c.isLivePlayback){if(void 0===b)if(a.D)if(a.C)b=7500;else{var d;b=(null==(d=a.heartbeatParams)?0:d.interval)?1E3*a.heartbeatParams.interval:a.getVideoData().nO||6E4}else b=1E3;a.u.start(b)}}},U$a=function(a,b,c){b.Jm&&(c=g.ii(c,{internalipoverride:b.Jm}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.lc&&(d.kpt=b.lc);c=g.ii(c,d);g.Su(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.u.isActive()&&D6(a)){a.I.reset();a.sequenceNumber++;e=e.responseText;var f=R$a(e);if(f){a.player.Qa("onHeartbeat",f);var h="ok"===f.status?f.stop_heartbeat?2:0:"stop"===f.status?1:"live_stream_offline"===f.status?0:-1}else h=(h=e.match(S$a))?"0"===h[1]?0:1:-1;T$a(a,f,e,h)}},
onError:function(e){D6(a)&&F6(a,!0,"net-"+e.status)},
onTimeout:function(){D6(a)&&F6(a,!0,"timeout")},
withCredentials:!0})},I$a=function(a,b,c){var d;
if(null!=(d=a.heartbeatParams)&&d.url){var e=g.ii(a.heartbeatParams.url,{request_id:g.mta()});c.Ja&&(e=g.ii(e,{vvt:c.Ja}),c.mdxEnvironment&&(e=g.ii(e,{mdx_environment:c.mdxEnvironment})));g.rH(b,c.oauthToken).then(function(f){f&&(e=g.ii(e,{access_token:f}));U$a(a,c,e)})}},D6=function(a){var b=a.getVideoData();
return 3===a.player.getPresentingPlayerType()||g.U(a.player.Db(a.getPlayerType()),4)?!1:Q$a(a)||b.isLivePlayback?!0:(G6(a),!1)},K$a=function(a,b,c){var d,e={videoId:c.videoId,
sequenceNumber:a.sequenceNumber,heartbeatServerData:null!=(d=a.oa)?d:c.heartbeatServerData};a.Y=a.attestationResponse;c.il&&(e.attestationResponse=a.Y);var f=g.$N(c),h;d=null!=(h=f.client)?h:{};d.utcOffsetMinutes=a.utcOffsetMinutes;e.context=f;e.cpn=c.clientPlaybackNonce;if(h="undefined"!==typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)d.timeZone=h;h={heartbeatChecks:[]};if(d=c.getPlayerResponse())c.heartbeatToken&&(e.heartbeatToken=c.heartbeatToken),(d=d.playabilityStatus)&&
(d=d.liveStreamability)&&d.liveStreamabilityRenderer&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");if(g.kH(b)){h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED");f=V$a(a);d={};null!==f&&(d.clientPlayerPositionUtcMillis=f);var l,m;f=(null==(m=null==(l=a.player.vb())?void 0:g.LP(l))?void 0:m.freePreviewWatchedDuration)||0;0<f&&(d.freePreviewWatchedDuration={seconds:""+f});h.unpluggedParams=d}e.heartbeatRequestParams=
h;c.isLivePlayback&&(l=V$a(a),null!==l&&(e.playbackState||(e.playbackState={}),e.playbackState.playbackPosition={utcTimeMillis:l}));var n={timeout:3E4,onSuccess:function(p){if(!a.u.isActive()&&D6(a)){var q=a.getVideoData(),r=q.il&&null==a.Y,w;q.il=!(null==(w=p.heartbeatAttestationConfig)||!w.requiresAttestation)||r;r=p.playabilityStatus;w=JSON.stringify(r)||"{}";p.authenticationMismatch&&a.player.va("authshear",{});var y=-1;var z=p.playabilityStatus;z&&(a.player.Qa("onHeartbeat",z),"OK"===z.status?
y=p.stopHeartbeat?2:0:"UNPLAYABLE"===z.status?y=1:"LIVE_STREAM_OFFLINE"===z.status&&(y=0));a.sequenceNumber&&-1===y||a.I.reset();a.sequenceNumber++;p.heartbeatServerData&&(a.oa=p.heartbeatServerData);p.playerCueRanges&&0<p.playerCueRanges.length&&(q.cueRanges=p.playerCueRanges,q.ma("dataupdated"));T$a(a,r,w,y)}},
onError:function(p){D6(a)&&F6(a,!0,"net-"+p.status)},
onTimeout:function(){D6(a)&&F6(a,!0,"timeout")}};
g.rH(b,g.oJ(c)).then(function(p){p&&(n.MO="Bearer "+p);g.vx(a.ea,"player/heartbeat",e,n)})},T$a=function(a,b,c,d){-1===d?(b="decode "+g.Cc(c,3),F6(a,!1,b)):2===d?(G6(a),a.D=!0):(a.T=0,a.u.stop(),1===d?(a.D=!1,a.player.wg("heartbeat.stop",2,a.rf(c)),g.cw("heartbeatActionPlayerHalted",W$a(b))):(a.D=!0,c=0,a.C&&b&&(c=M$a(a,b),a.player.ma("livestatedata",b)),c?E6(a,c):E6(a)))},M$a=function(a,b){var c=b.liveStreamability&&b.liveStreamability.liveStreamabilityRenderer,d=!(!c||!(c.switchStreamsImmediately||
c.transitionTiming&&"STREAM_TRANSITION_TIMING_IMMEDIATELY"===c.transitionTiming)),e=X$a(c),f=a.getVideoData(),h=a.player.Db(a.getPlayerType()),l=h.Rc()&&!g.cJ(f)&&!a.player.isAtLiveHead(a.getPlayerType());
if(f.V().C){var m,n=(null==(m=a.player.Yd())?void 0:m.Yb())||{};n.status=b.status||"";n.dvr=""+ +l;n["switch"]=""+ +d;n.ended=""+ +!(!c||!c.displayEndscreen);a.player.va("heartbeat",n)}if(l&&!d)return e;d=c&&c.streamTransitionEndpoint&&g.O(c.streamTransitionEndpoint,g.OH);if("STREAM_TRANSITION_TIMING_AT_STREAM_END"===(c&&c.transitionTiming))a.getVideoData().transitionEndpointAtEndOfStream=d;else{if(l=d)(l=d&&d.videoId)?(a.player.xm(l,{autonav:"1"},void 0,!0,!0,d,g.oJ(a.getVideoData())),a.TD("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE",
"HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",b),l=!0):l=!1;if(l)return e}if("OK"===b.status.toUpperCase()){d=c&&c.broadcastId;l=a.j&&a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer&&a.j.liveStreamability.liveStreamabilityRenderer.broadcastId;m=d!==l&&null!=d;if(!f.hlsvp&&!f.yb||m){var p={video_id:f.videoId};f.JG&&(p.is_live_destination="1");a.player.N("web_player_heartbeat_request_watch_next")||(p.disable_watch_next=!0,p.raw_watch_next_response=f.watchNextResponse);
p.autonav_state=f.autonavState;p.oauth_token=f.oauthToken;p.force_gvi=f.Hm;p.Fk=f.Fk;f.J&&(p.vss_credentials_token=f.J,p.vss_credentials_token_type=f.lj);f.Ja&&(p.vvt=f.Ja);c=void 0;f.hlsvp||f.yb?m&&(c=new C6("broadcastIdChanged",l+","+d),a.TD("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",b)):(d&&(c=new C6("formatsReceived",""+d)),a.TD("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",b));a.player.loadVideoByPlayerVars(p,
void 0,void 0,void 0,c);return e}a.player.Of("heartbeat",a.getPlayerType())}c&&c.displayEndscreen&&(a.offlineSlate?(a=a.offlineSlate,a.I=!0,a.sb&&a.api.sx()):g.eL(h)&&(f=(null==(p=a.player.Yd())?void 0:p.Yb())||{},a.player.va("hbse",f,!0),a.player.sx(),a.player.Qa("onLiveMediaEnded",b)));return e},X$a=function(a){var b=0;
a&&a.pollDelayMs&&(a=Number(a.pollDelayMs))&&(b=a);return b},F6=function(a,b,c){var d=a.player.V();
if(!a.u.isActive()){a.u.stop();a.T++;var e=b?"heartbeat.net":"heartbeat.servererror";var f=a.getVideoData();if(f.pO||b&&!g.XI(a.getVideoData())&&!Q$a(a)&&f.isLivePlayback)f=!1;else{var h,l;(null==(l=a.heartbeatParams)?0:l.kx)?h=a.heartbeatParams.kx:h=f.oO||5;f=a.T>=h}f?(g.cw("heartbeatActionPlayerHalted",b?{enforcedPolicyToHaltOnNetworkFailure:!0}:W$a()),(b=a.getVideoData())&&b.isLivePlayback?a.player.wg(e,1,"Video playback interrupted. Please try again.",c):a.player.wg(e,1,"Sorry, there was an error licensing this video.",
c)):(d.N("html5_report_non_fatal_heartbeat_error")&&a.player.Ep(e,{msg:c}),E6(a,a.I.getValue()),g.Uh(a.I))}},W$a=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},G6=function(a){a.T=0;
a.u.stop();a.D=!1;a.sequenceNumber=0},L$a=function(a){var b=a.getVideoData(),c=a.player.V();
if(b.isLivePlayback)if(g.YF(c.B)){a.C=!0;a.J=!0;if(!g.ZG(c)||g.kH(c))a.offlineSlate=new F$a(a.player),g.M(a,a.offlineSlate),g.OO(a.player,a.offlineSlate.element,4);(b=b.getPlayerResponse())&&b.playabilityStatus&&(a.j=b.playabilityStatus);var d;if("UNPLAYABLE"!==(null==(d=a.j)?void 0:d.status)||a.player.N("stop_heartbeat_on_unplayable_live_videos_killswitch"))a.j?(d=X$a(a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer))?E6(a,d):E6(a,7500):E6(a,1E3)}else a.player.wg("html5.unsupportedlive",
2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");else g.Sb(b.Ba,"heartbeat")&&a.player.Of("heartbeat",a.getPlayerType())},V$a=function(a){return(a=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(a)?""+Math.floor(1E3*a):null},R$a=function(a){try{var b=JSON.parse(a);
return null!=b?b:void 0}catch(c){}},P$a=["ATTESTATION_ERROR_UNKNOWN",
"ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],Y$a={coa:["BC","AD"],boa:["Before Christ","Anno Domini"],XHa:"JFMAMJJASOND".split(""),LVa:"JFMAMJJASOND".split(""),vGa:"January February March April May June July August September October November December".split(" "),KVa:"January February March April May June July August September October November December".split(" "),XRa:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
NVa:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),T4a:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),PVa:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),bTa:"Sun Mon Tue Wed Thu Fri Sat".split(" "),OVa:"Sun Mon Tue Wed Thu Fri Sat".split(" "),YHa:"SMTWTFS".split(""),MVa:"SMTWTFS".split(""),YRa:["Q1","Q2","Q3","Q4"],KPa:["1st quarter","2nd quarter","3rd quarter","4th quarter"],q$:["AM","PM"],Mla:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],
IYa:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],Nla:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],fV:6,U4a:[5,6],gV:5},Z$a=Y$a;Z$a=Y$a;g.k=v$a.prototype;g.k.HP=Z$a.fV;g.k.IP=Z$a.gV;g.k.clone=function(){var a=new v$a(this.date);a.HP=this.HP;a.IP=this.IP;return a};
g.k.getFullYear=function(){return this.date.getFullYear()};
g.k.getYear=function(){return this.getFullYear()};
g.k.getMonth=function(){return this.date.getMonth()};
g.k.getDate=function(){return this.date.getDate()};
g.k.getTime=function(){return this.date.getTime()};
g.k.getDay=function(){return this.date.getDay()};
g.k.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.k.getUTCMonth=function(){return this.date.getUTCMonth()};
g.k.getUTCDate=function(){return this.date.getUTCDate()};
g.k.getUTCDay=function(){return this.date.getDay()};
g.k.getUTCHours=function(){return this.date.getUTCHours()};
g.k.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.k.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.k.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
g.k.setFullYear=function(a){this.date.setFullYear(a)};
g.k.setYear=function(a){this.setFullYear(a)};
g.k.setMonth=function(a){this.date.setMonth(a)};
g.k.setDate=function(a){this.date.setDate(a)};
g.k.setTime=function(a){this.date.setTime(a)};
g.k.setUTCFullYear=function(a){this.date.setUTCFullYear(a)};
g.k.setUTCMonth=function(a){this.date.setUTCMonth(a)};
g.k.setUTCDate=function(a){this.date.setUTCDate(a)};
g.k.add=function(a){if(a.u||a.j){var b=this.getMonth()+a.j+12*a.u,c=this.getYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);a:{switch(b){case 1:var d=0!=c%4||0==c%100&&0!=c%400?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.days&&(c=this.getYear(),b=0<=c&&99>=c?-1900:0,a=new Date((new Date(c,this.getMonth(),this.getDate(),12)).getTime()+864E5*a.days),this.setDate(1),this.setFullYear(a.getFullYear()+
b),this.setMonth(a.getMonth()),this.setDate(a.getDate()),y6(this,a.getDate()))};
g.k.equals=function(a){return!(!a||this.getYear()!=a.getYear()||this.getMonth()!=a.getMonth()||this.getDate()!=a.getDate())};
g.k.toString=function(){var a=this.getFullYear(),b=0>a?"-":1E4<=a?"+":"";return[b+r$a(Math.abs(a),b?6:4),r$a(this.getMonth()+1,2),r$a(this.getDate(),2)].join("")+""};
g.k.valueOf=function(){return this.date.valueOf()};var $$a=new g.dp("addUpcomingEventReminderEndpoint");var aab=new g.dp("removeUpcomingEventReminderEndpoint");var bab=new g.dp("updateUpcomingEventReminderButtonStateCommand");var y$a=new g.dp("upcomingEventReminderButtonRenderer"),E$a=new g.dp("upcomingEventReminderButtonStateRenderer");g.v(z6,g.QO);z6.prototype.hide=function(){this.buttonElement&&this.buttonElement.removeAttribute("aria-haspopup");g.QO.prototype.hide.call(this)};
z6.prototype.show=function(){this.buttonElement&&this.buttonElement.setAttribute("aria-haspopup","true");g.QO.prototype.show.call(this)};
z6.prototype.ra=function(){g.Xe(this.j);g.QO.prototype.ra.call(this)};g.v(A6,g.V);
A6.prototype.D=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.B(a.toggledServiceEndpoint):this.B(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;B6(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.j&&this.j.sb)this.j.wb();else{var b=B$a(this);b&&this.B(b.serviceEndpoint||b.command);b=(null==(a=g.O(null==b?void 0:b.command,g.ZM))?void 0:a.commands)||[];a:{a=g.t(b);for(var c=a.next();!c.done;c=a.next()){var d=b=void 0;if(c=null==(b=g.O(c.value,
g.j3a))?void 0:null==(d=b.popup)?void 0:d.menuPopupRenderer){a=c;break a}}a=void 0}this.j||(this.j=new z6(this.G,this.buttonElement),this.j.Ca(this.element),g.M(this,this.j),this.j.subscribe("reminderMenuItemClicked",this.B,this));b=this.j;b.menuPopupRenderer=a;x$a(b)}};
A6.prototype.B=function(a){var b=g.O(a,$$a),c=g.O(a,aab);if(a&&(b||c)){if(b){var d=b;var e="notification/add_upcoming_event_reminder"}else c&&(d=c,e="notification/remove_upcoming_event_reminder");if(e&&d&&d.params)for(D$a(this,e,d.params),a=g.t(d.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&g.O(b,bab)){this.u=g.O(b,bab).state;B6(this);break}}};g.v(F$a,g.V);g.k=F$a.prototype;g.k.getPlayerType=function(){if(8===this.api.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.La=function(a){var b,c,d=null==a?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:c.offlineSlate;if(d){this.u=a;b=d.liveStreamOfflineSlateRenderer;b.canShowCountdown?this.pU():G$a(this,b);var e,f,h,l;if(c=null==a?void 0:null==(e=a.liveStreamability)?void 0:null==(f=e.liveStreamabilityRenderer)?void 0:null==(h=f.offlineSlate)?void 0:null==(l=h.liveStreamOfflineSlateRenderer)?void 0:l.thumbnail){e=0;f=null;h=c.thumbnails;for(l=0;l<h.length;l++)h[l].width>
e&&(e=h[l].width||0,f=h[l].url);f&&(this.background.style.backgroundImage="url("+f+")")}else this.background.style.backgroundImage="";b.actionButtons||b.reminderButton?(this.j||(this.j=new A6(this.api),this.j.Ca(this.Da("ytp-offline-slate-buttons")),g.M(this,this.j)),z$a(this.j,b.actionButtons&&b.actionButtons[0],b.reminderButton)):this.j&&z$a(this.j,null,null);this.u=a}else this.u=null;this.tU()};
g.k.tU=function(a){if(8===this.api.getPresentingPlayerType())var b=!0;else{var c=this.api.Db(),d=this.getVideoData();b=d.isLivePlayback&&(g.eL(c)||g.U(c,2)||g.U(c,64));var e=2===d.autonavState&&g.U(c,2);c=c.Rc()&&!g.cJ(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.u?this.sb?(null==a?0:g.qK(a,2))&&!this.getVideoData().hk&&(g.no(this.element,"ytp-offline-slate-collapsed"),this.C.stop(),g.no(this.B,"ytp-offline-slate-bar-fade"),this.D.start()):(this.show(),this.C.start(),this.api.ma("offlineslatestatechange"),
this.I&&this.api.sx()):this.sb&&(this.hide(),this.api.ma("offlineslatestatechange"))};
g.k.pU=function(){var a,b,c,d,e=null==(a=this.u)?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:null==(d=c.offlineSlate)?void 0:d.liveStreamOfflineSlateRenderer;e&&(a=Math.floor(g.Sa()/1E3),b=e.canShowCountdown&&Number(e.scheduledStartTime),!b||b<=a?(G$a(this,e),this.countdownTimer.stop()):(G$a(this,e,g.fN(b-a)),g.eo(this.countdownTimer)))};
g.k.ra=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.V.prototype.ra.call(this)};C6.prototype.u=function(a){return this.trigger&&a.trigger?this.module===a.module&&this.trigger===a.trigger&&this.j===a.j:!1};
C6.prototype.isExpired=function(){return 6E4<(0,g.Q)()-this.B};
C6.prototype.toString=function(){return this.module+":"+this.trigger+":"+this.j};g.v(O$a,g.vP);g.k=O$a.prototype;g.k.ra=function(){G6(this);this.player.Df("heartbeat");g.vP.prototype.ra.call(this)};
g.k.onCueRangeEnter=function(){this.J=!0;E6(this,2E3)};
g.k.zA=function(a){this.heartbeatParams=a;E6(this,2E3)};
g.k.IV=function(a){var b;8===this.player.getPresentingPlayerType()||"UNPLAYABLE"===(null==(b=this.j)?void 0:b.status)&&!this.player.N("stop_heartbeat_on_unplayable_live_videos_killswitch")||(g.U(a.state,2)||g.U(a.state,64)?(G6(this),this.C&&(this.J=!0,E6(this,1E3))):(g.U(a.state,1)||g.U(a.state,8))&&E6(this,2E3))};
g.k.JV=function(){3!==this.player.getPresentingPlayerType()&&E6(this,2E3)};
g.k.getPlayerType=function(){if(8===this.player.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.Tj=function(a){switch(a){case 4:case 3:return!1}return!0};
g.k.TD=function(a,b,c){a={trigger:a,reason:b};c&&(a.serializedServerContext=c.additionalLoggingData);g.cw("heartbeatActionPlayerTransitioned",a)};
g.k.rf=function(a){var b="LICENSE",c=R$a(a);if(c)return c.reason||g.cQ[b]||"";(a=a.match(S$a))&&(a=Number(a[1]))&&(b=g.VEa(a));return g.cQ[b]||""};
g.k.Yz=function(){return!!this.offlineSlate&&this.offlineSlate.sb};
var S$a=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.uP("heartbeat",O$a);})(_yt_player);
